src/webapp/app/home/forms.py
# -*- coding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField
from wtforms.validators import DataRequired


class ClassificationForm(FlaskForm):
    """
    Form for adding, editing, removing classifications
    """
    pattern = StringField('Pattern', validators=[DataRequired()],
                          render_kw={"placeholder": "Regular Expression..."})
    brand = StringField('Brand', render_kw={"placeholder": "Brand..."})
    sub_brand = StringField('Sub Brand',
                            render_kw={"placeholder": "Sub Brand..."})
    dsp = StringField('DSP', render_kw={"placeholder": "DSP..."})
    use_campaign_id = BooleanField('Use Campaign ID')
    use_campaign = BooleanField('Use Campaign')
    use_placement_id = BooleanField('Use Placement ID (DCM)')
    use_placement = BooleanField('Use Placement (DCM)')
    submit = SubmitField('Submit')

src/webapp/app/home/__init__.py
# third-party imports
from flask import Blueprint

home = Blueprint('home', __name__)

# local imports
from . import views

src/webapp/app/home/views.py
# python standard
from datetime import datetime

# third-party imports
from flask import flash, redirect, render_template, url_for, jsonify, request
from flask_login import login_required

# local imports
from . import home
from .forms import ClassificationForm
from .. import db
from ..models import Report, Classification, DCM, DSP
from ..queries import GENERATE_CLASSIFIED, GENERATE_REPORT


@home.route('/')
def homepage():
    """
    Render the homepage template on the / route
    """
    return render_template('home/index.html', title="Welcome")


@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    return render_template('home/dashboard.html', title="Dashboard")


@home.route('/report')
@login_required
def report_date():
    """
    Return full report data as Json
    """
    try:
        def parse_date(dt):
            if dt:
                try:
                    dt = datetime.strptime(dt, "%Y-%m-%d")
                except Exception:
                    dt = None
            return dt

        start_date = parse_date(request.args.get('start_date',
                                                 default=None, type=None))
        end_date = parse_date(request.args.get('end_date',
                                               default=None, type=None))

        results = []
        if start_date and end_date:
            results = Report.query\
                            .filter(Report.date >= start_date)\
                            .filter(Report.date <= end_date)
        elif start_date:
            results = Report.query.filter(Report.date >= start_date)
        elif end_date:
            results = Report.query.filter(Report.date <= end_date)
        else:
            results = Report.query.all()

        return jsonify({
            "status": "success",
            "data": [r.serialize for r in results]
        })
    except Exception as err:
        print(str(err))
        return jsonify({
            "status": "fail",
            "data": []
        })


@home.route('/last_update')
@login_required
def last_update():
    """
    Get last update date
    """
    try:
        last = Report.query.order_by("updated_at desc").first().updated_at
        return jsonify({
            "status": "success",
            "last_update": last
        })
    except Exception as err:
        print(str(err))
        return jsonify({
            "status": "fail",
            "data": []
        })


@home.route('/classifications', methods=['GET', 'POST'])
@login_required
def list_classifications():
    """
    List all classifications
    """
    classifications = Classification.query.all()

    return render_template('home/classifications.html',
                           classifications=classifications,
                           title="Classifications")


@home.route('/classifications/add', methods=['GET', 'POST'])
@login_required
def add_classification():
    """
    Add a classification to the database
    """
    add_classification = True

    form = ClassificationForm()
    if form.validate_on_submit():
        classification = Classification(pattern=form.pattern.data,
                                        brand=form.brand.data,
                                        sub_brand=form.sub_brand.data,
                                        dsp=form.dsp.data,
                                        use_campaign_id=form.use_campaign_id.data,
                                        use_campaign=form.use_campaign.data,
                                        use_placement_id=form.use_placement_id.data,
                                        use_placement=form.use_placement.data)
        try:
            # add classification to the database
            db.session.add(classification)
            db.session.commit()
            flash('You have successfully added a new classification.')
        except Exception:
            # in case classification name already exists
            flash('Error: classification name already exists.')

        # redirect to classifications page
        return redirect(url_for('home.list_classifications'))

    # load classification template
    return render_template('home/classification.html', action="Add",
                           add_classification=add_classification, form=form,
                           title="Add Classification")


@home.route('/classifications/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_classification(id):
    """
    Edit a classification
    """

    add_classification = False

    classification = Classification.query.get_or_404(id)
    form = ClassificationForm(obj=classification)
    if form.validate_on_submit():
        classification.brand = form.brand.data
        classification.sub_brand = form.sub_brand.data
        classification.dsp = form.dsp.data
        classification.use_campaign_id = form.use_campaign_id.data
        classification.use_campaign = form.use_campaign.data
        classification.use_placement_id = form.use_placement_id.data
        classification.use_placement = form.use_placement.data
        db.session.commit()
        flash('You have successfully edited the classification.')

        # redirect to the classifications page
        return redirect(url_for('home.list_classifications'))

    form.brand.data = classification.brand
    form.sub_brand.data = classification.sub_brand
    form.dsp.data = classification.dsp
    form.use_campaign_id.data = classification.use_campaign_id
    form.use_campaign.data = classification.use_campaign
    form.use_placement_id.data = classification.use_placement_id
    form.use_placement.data = classification.use_placement

    return render_template('home/classification.html', action="Edit",
                           add_classification=add_classification, form=form,
                           classification=classification,
                           title="Edit Classification")


@home.route('/classification/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_classification(id):
    """
    Delete a classification from the database
    """
    classification = Classification.query.get_or_404(id)
    db.session.delete(classification)
    db.session.commit()
    flash('You have successfully deleted the classification.')

    # redirect to the classifications page
    return redirect(url_for('home.list_classifications'))

    return render_template(title="Delete Classification")


@home.route('/classification/reset', methods=['GET'])
@login_required
def reset_classifications():
    """
    Reset all classifications, might take a while
    """
    try:
        DCM.query.delete()
        DSP.query.delete()
        Report.query.delete()
        db.session.execute(GENERATE_CLASSIFIED)
        db.session.execute(GENERATE_REPORT)
        db.session.commit()
        return jsonify({
            "status": "success"
        })
    except Exception as err:
        print(str(err))
        return jsonify({
            "status": "fail"
        })

src/webapp/app/templates/home/classification.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    {% if add_classification %}
        Add Classification
    {% else %}
        Edit Classification
    {% endif %}
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            {% if add_classification %}
                <h1>Add Classification</h1>
            {% else %}
                <h1>Edit Classification</h1>
            {% endif %}
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

src/webapp/app/templates/home/classifications.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Classifications{% endblock %}
{% block body %}
<div class='notifications bottom-right'></div>
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Classifications</h1>
        {% if classifications %}
          <hr class="intro-divider">
          <div class="big-center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th> Pattern* </th>
                  <th> Brand </th>
                  <th> Sub Brand </th>
                  <th> DSP </th>
                  <th> Use Campaign Id </th>
                  <th> Use Campaign </th>
                  <th> Use Placement Id** </th>
                  <th> Use Placement** </th>
                  <th> Edit </th>
                  <th> Delete </th>
                </tr>
              </thead>
              <tbody>
              {% for classification in classifications %}
                <tr>
                  <td> {{ classification.pattern }} </td>
                  <td> {{ classification.brand }} </td>
                  <td> {{ classification.sub_brand }} </td>
                  <td> {{ classification.dsp }} </td>
                  <td> {{ classification.use_campaign_id }} </td>
                  <td> {{ classification.use_campaign }} </td>
                  <td> {{ classification.use_placement_id }} </td>
                  <td> {{ classification.use_placement }} </td>
                  <td>
                    <a href="{{ url_for('home.edit_classification', id=classification.id) }}">
                      <i class="fa fa-pencil"></i> Edit 
                    </a>
                  </td>
                  <td>
                    <a href="{{ url_for('home.delete_classification', id=classification.id) }}">
                      <i class="fa fa-trash"></i> Delete 
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
            <p>* Pattern will always be regex and ignore case sensitivity</p>
            <p>** Valid only in DCM files</p>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No classifications have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
        
          <div class="container">
              <div class="alert alert-success" style="display: none;" id="success-alert">
                <strong>Success!</strong> New classifications applied.
              </div>
              <div class="alert alert-danger" style="display: none;" id="danger-alert">
                <strong>Error!</strong> Something went wront.
              </div>
          </div>
          <a href="{{ url_for('home.add_classification') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Add Classification
          </a>
          
          <a href="#" class="btn btn-default btn-lg" id="refresh_classification">
            <i class="fa fa-refresh" id="refresh_icon"></i>
            Refresh Classification
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

<script type=text/javascript>

$(function() {
    $('#refresh_classification').bind('click', function () {
        $('#refresh_icon').addClass('fa-spin');
        $('#success-alert').hide();
        $('#danger-alert').hide();
        $.ajax({
          url: '/classification/reset',
          success: function (data) {
              $('#refresh_icon').removeClass('fa-spin');
              if (data.status == "success") {
                  $('#success-alert').show();
              } else {
                  $('#danger-alert').show();
              }
          },
          fail: function(data) {
              $('#refresh_icon').removeClass('fa-spin');
              $('#danger-alert').show();
          }
        });
    });
});
</script>
{% endblock %}

src/webapp/app/templates/home/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block body %}
<div class="dashboard-header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1>DSP Report <small>Last update: <span id="last_update">-/-</span></small></h1>
                <form class="form-inline">
                    <div class="form-group">
                        <label for="start_date">Start Date</label>
                        <input type="date" class="form-control" id="start_date">
                    </div>
                    <div class="form-group">
                        <label for="end_date">End Date</label>
                        <input type="date" class="form-control" id="end_date">
                    </div>
                    <button id="get_report" type="button" class="btn btn-default"><i class="fa fa-filter"></i> Filter</button>
                </form>
                <hr>
                <table id="report_table" class="display" style="width:100%">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Brand</th>
                            <th>Sub Brand</th>
                            <th>Ad Campaign Id</th>
                            <th>Ad Campaign</th>
                            <th>DSP</th>
                            <th>DSP Campaign Id</th>
                            <th>DSP Campaign</th>
                            <th>Ad Impressions</th>
                            <th>Ad Clicks</th>
                            <th>Ad Reach</th>
                            <th>DSP Impressions</th>
                            <th>DSP Clicks</th>
                            <th>DSP Cost</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Date</th>
                            <th>Brand</th>
                            <th>Sub Brand</th>
                            <th>Ad Campaign Id</th>
                            <th>Ad Campaign</th>
                            <th>DSP</th>
                            <th>DSP Campaign Id</th>
                            <th>DSP Campaign</th>
                            <th>Ad Impressions</th>
                            <th>Ad Clicks</th>
                            <th>Ad Reach</th>
                            <th>DSP Impressions</th>
                            <th>DSP Clicks</th>
                            <th>DSP Cost</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>

<script type=text/javascript>
$(function() {
    var table = $('#report_table').DataTable();
    $("#report_table").hide();
    var refresh_table = function () {
        var start_date = $('#start_date').val();
        var end_date = $('#end_date').val();
        
        $.ajax({
          url: '/last_update',
          success: function (data) {
              if (data.status == "success") {
                  $('#last_update').text(data.last_update);
              }
          }
        });
        
        $("#report_table").show();

        table.destroy();
        table = $('#report_table').DataTable( {
            ajax: '/report?start_date=' + start_date + '&end_date=' + end_date,
            columns: [
                { data: 'date' },
                { data: 'brand' },
                { data: 'sub_brand' },
                { data: 'ad_campaign_id' },
                { data: 'ad_campaign' },
                { data: 'dsp' },
                { data: 'dsp_campaign_id' },
                { data: 'dsp_campaign' },
                { data: 'ad_impressions' },
                { data: 'ad_clicks' },
                { data: 'ad_reach' },
                { data: 'dsp_impressions' },
                { data: 'dsp_clicks' },
                { data: 'dsp_cost' },
            ]
        } );
    };
    refresh_table();
    $('#get_report').bind('click', frefresh_table);
});
</script>

{% endblock %}

src/webapp/app/templates/home/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Dream Reports</h1>
                    <h3>The best reports you'll ever see!</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}